/*
 * EconomyKit API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EconomyKit.UnityClient.Api;
using EconomyKit.UnityClient.Model;
using EconomyKit.UnityClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EconomyKit.UnityClient.Test
{
    /// <summary>
    ///  Class for testing CommodityStackCreateBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CommodityStackCreateBodyTests
    {
        // TODO uncomment below to declare an instance variable for CommodityStackCreateBody
        //private CommodityStackCreateBody instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CommodityStackCreateBody
            //instance = new CommodityStackCreateBody();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CommodityStackCreateBody
        /// </summary>
        [Test]
        public void CommodityStackCreateBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CommodityStackCreateBody
            //Assert.IsInstanceOf(typeof(CommodityStackCreateBody), instance);
        }


        /// <summary>
        /// Test the property 'Player'
        /// </summary>
        [Test]
        public void PlayerTest()
        {
            // TODO unit test for the property 'Player'
        }
        /// <summary>
        /// Test the property 'Commodity'
        /// </summary>
        [Test]
        public void CommodityTest()
        {
            // TODO unit test for the property 'Commodity'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Test]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'DecimalPlaces'
        /// </summary>
        [Test]
        public void DecimalPlacesTest()
        {
            // TODO unit test for the property 'DecimalPlaces'
        }

    }

}
