/*
 * EconomyKit API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EconomyKit.UnityClient.Api;
using EconomyKit.UnityClient.Model;
using EconomyKit.UnityClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EconomyKit.UnityClient.Test
{
    /// <summary>
    ///  Class for testing FetchPlayerRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FetchPlayerRequestTests
    {
        // TODO uncomment below to declare an instance variable for FetchPlayerRequest
        //private FetchPlayerRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FetchPlayerRequest
            //instance = new FetchPlayerRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FetchPlayerRequest
        /// </summary>
        [Test]
        public void FetchPlayerRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" FetchPlayerRequest
            //Assert.IsInstanceOf(typeof(FetchPlayerRequest), instance);
        }


        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Test]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }
        /// <summary>
        /// Test the property 'IdType'
        /// </summary>
        [Test]
        public void IdTypeTest()
        {
            // TODO unit test for the property 'IdType'
        }
        /// <summary>
        /// Test the property 'IdPayload'
        /// </summary>
        [Test]
        public void IdPayloadTest()
        {
            // TODO unit test for the property 'IdPayload'
        }

    }

}
