/*
 * EconomyKit API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EconomyKit.UnityClient.Api;
using EconomyKit.UnityClient.Model;
using EconomyKit.UnityClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EconomyKit.UnityClient.Test
{
    /// <summary>
    ///  Class for testing GetStorefrontQuery
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetStorefrontQueryTests
    {
        // TODO uncomment below to declare an instance variable for GetStorefrontQuery
        //private GetStorefrontQuery instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetStorefrontQuery
            //instance = new GetStorefrontQuery();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetStorefrontQuery
        /// </summary>
        [Test]
        public void GetStorefrontQueryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" GetStorefrontQuery
            //Assert.IsInstanceOf(typeof(GetStorefrontQuery), instance);
        }


        /// <summary>
        /// Test the property 'Storefront'
        /// </summary>
        [Test]
        public void StorefrontTest()
        {
            // TODO unit test for the property 'Storefront'
        }
        /// <summary>
        /// Test the property 'App'
        /// </summary>
        [Test]
        public void AppTest()
        {
            // TODO unit test for the property 'App'
        }
        /// <summary>
        /// Test the property 'Player'
        /// </summary>
        [Test]
        public void PlayerTest()
        {
            // TODO unit test for the property 'Player'
        }

    }

}
