/*
 * EconomyKit API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EconomyKit.UnityClient.Api;
using EconomyKit.UnityClient.Model;
using EconomyKit.UnityClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EconomyKit.UnityClient.Test
{
    /// <summary>
    ///  Class for testing InventoryEntry
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InventoryEntryTests
    {
        // TODO uncomment below to declare an instance variable for InventoryEntry
        //private InventoryEntry instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InventoryEntry
            //instance = new InventoryEntry();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InventoryEntry
        /// </summary>
        [Test]
        public void InventoryEntryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" InventoryEntry
            //Assert.IsInstanceOf(typeof(InventoryEntry), instance);
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'UniqueItem'
        /// </summary>
        [Test]
        public void UniqueItemTest()
        {
            // TODO unit test for the property 'UniqueItem'
        }
        /// <summary>
        /// Test the property 'CommodityStack'
        /// </summary>
        [Test]
        public void CommodityStackTest()
        {
            // TODO unit test for the property 'CommodityStack'
        }

    }

}
