/*
 * EconomyKit API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EconomyKit.UnityClient.Api;
using EconomyKit.UnityClient.Model;
using EconomyKit.UnityClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EconomyKit.UnityClient.Test
{
    /// <summary>
    ///  Class for testing ListTradesRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListTradesRequestTests
    {
        // TODO uncomment below to declare an instance variable for ListTradesRequest
        //private ListTradesRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ListTradesRequest
            //instance = new ListTradesRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ListTradesRequest
        /// </summary>
        [Test]
        public void ListTradesRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ListTradesRequest
            //Assert.IsInstanceOf(typeof(ListTradesRequest), instance);
        }


        /// <summary>
        /// Test the property 'Player'
        /// </summary>
        [Test]
        public void PlayerTest()
        {
            // TODO unit test for the property 'Player'
        }
        /// <summary>
        /// Test the property 'ActiveOnly'
        /// </summary>
        [Test]
        public void ActiveOnlyTest()
        {
            // TODO unit test for the property 'ActiveOnly'
        }

    }

}
