/*
 * EconomyKit API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EconomyKit.UnityClient.Api;
using EconomyKit.UnityClient.Model;
using EconomyKit.UnityClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EconomyKit.UnityClient.Test
{
    /// <summary>
    ///  Class for testing PlaceTradeReqRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PlaceTradeReqRequestTests
    {
        // TODO uncomment below to declare an instance variable for PlaceTradeReqRequest
        //private PlaceTradeReqRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PlaceTradeReqRequest
            //instance = new PlaceTradeReqRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PlaceTradeReqRequest
        /// </summary>
        [Test]
        public void PlaceTradeReqRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" PlaceTradeReqRequest
            //Assert.IsInstanceOf(typeof(PlaceTradeReqRequest), instance);
        }


        /// <summary>
        /// Test the property 'Sender'
        /// </summary>
        [Test]
        public void SenderTest()
        {
            // TODO unit test for the property 'Sender'
        }
        /// <summary>
        /// Test the property 'Recipient'
        /// </summary>
        [Test]
        public void RecipientTest()
        {
            // TODO unit test for the property 'Recipient'
        }
        /// <summary>
        /// Test the property 'SentCommodities'
        /// </summary>
        [Test]
        public void SentCommoditiesTest()
        {
            // TODO unit test for the property 'SentCommodities'
        }
        /// <summary>
        /// Test the property 'SentUniqueItems'
        /// </summary>
        [Test]
        public void SentUniqueItemsTest()
        {
            // TODO unit test for the property 'SentUniqueItems'
        }
        /// <summary>
        /// Test the property 'ReceivedCommodities'
        /// </summary>
        [Test]
        public void ReceivedCommoditiesTest()
        {
            // TODO unit test for the property 'ReceivedCommodities'
        }
        /// <summary>
        /// Test the property 'ReceivedUniqueItems'
        /// </summary>
        [Test]
        public void ReceivedUniqueItemsTest()
        {
            // TODO unit test for the property 'ReceivedUniqueItems'
        }

    }

}
