/*
 * EconomyKit API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EconomyKit.UnityClient.Api;
using EconomyKit.UnityClient.Model;
using EconomyKit.UnityClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EconomyKit.UnityClient.Test
{
    /// <summary>
    ///  Class for testing StorefrontItemResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StorefrontItemResultTests
    {
        // TODO uncomment below to declare an instance variable for StorefrontItemResult
        //private StorefrontItemResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StorefrontItemResult
            //instance = new StorefrontItemResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StorefrontItemResult
        /// </summary>
        [Test]
        public void StorefrontItemResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" StorefrontItemResult
            //Assert.IsInstanceOf(typeof(StorefrontItemResult), instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Test]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'SortWeight'
        /// </summary>
        [Test]
        public void SortWeightTest()
        {
            // TODO unit test for the property 'SortWeight'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Test]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
        /// <summary>
        /// Test the property 'PriceUsd'
        /// </summary>
        [Test]
        public void PriceUsdTest()
        {
            // TODO unit test for the property 'PriceUsd'
        }
        /// <summary>
        /// Test the property 'PriceEur'
        /// </summary>
        [Test]
        public void PriceEurTest()
        {
            // TODO unit test for the property 'PriceEur'
        }
        /// <summary>
        /// Test the property 'PriceGbp'
        /// </summary>
        [Test]
        public void PriceGbpTest()
        {
            // TODO unit test for the property 'PriceGbp'
        }
        /// <summary>
        /// Test the property 'PriceJpy'
        /// </summary>
        [Test]
        public void PriceJpyTest()
        {
            // TODO unit test for the property 'PriceJpy'
        }
        /// <summary>
        /// Test the property 'PriceKrw'
        /// </summary>
        [Test]
        public void PriceKrwTest()
        {
            // TODO unit test for the property 'PriceKrw'
        }
        /// <summary>
        /// Test the property 'Image'
        /// </summary>
        [Test]
        public void ImageTest()
        {
            // TODO unit test for the property 'Image'
        }
        /// <summary>
        /// Test the property 'CommodityStacks'
        /// </summary>
        [Test]
        public void CommodityStacksTest()
        {
            // TODO unit test for the property 'CommodityStacks'
        }
        /// <summary>
        /// Test the property 'UniqueItems'
        /// </summary>
        [Test]
        public void UniqueItemsTest()
        {
            // TODO unit test for the property 'UniqueItems'
        }

    }

}
