/*
 * EconomyKit API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EconomyKit.UnityClient.Api;
using EconomyKit.UnityClient.Model;
using EconomyKit.UnityClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EconomyKit.UnityClient.Test
{
    /// <summary>
    ///  Class for testing StorefrontResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StorefrontResultTests
    {
        // TODO uncomment below to declare an instance variable for StorefrontResult
        //private StorefrontResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StorefrontResult
            //instance = new StorefrontResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StorefrontResult
        /// </summary>
        [Test]
        public void StorefrontResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" StorefrontResult
            //Assert.IsInstanceOf(typeof(StorefrontResult), instance);
        }


        /// <summary>
        /// Test the property 'StorefrontId'
        /// </summary>
        [Test]
        public void StorefrontIdTest()
        {
            // TODO unit test for the property 'StorefrontId'
        }
        /// <summary>
        /// Test the property 'AppId'
        /// </summary>
        [Test]
        public void AppIdTest()
        {
            // TODO unit test for the property 'AppId'
        }
        /// <summary>
        /// Test the property 'PlayerId'
        /// </summary>
        [Test]
        public void PlayerIdTest()
        {
            // TODO unit test for the property 'PlayerId'
        }
        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Test]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }

    }

}
