/*
 * EconomyKit API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EconomyKit.UnityClient.Api;
using EconomyKit.UnityClient.Model;
using EconomyKit.UnityClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EconomyKit.UnityClient.Test
{
    /// <summary>
    ///  Class for testing TradeRequestModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TradeRequestModelTests
    {
        // TODO uncomment below to declare an instance variable for TradeRequestModel
        //private TradeRequestModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TradeRequestModel
            //instance = new TradeRequestModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TradeRequestModel
        /// </summary>
        [Test]
        public void TradeRequestModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" TradeRequestModel
            //Assert.IsInstanceOf(typeof(TradeRequestModel), instance);
        }


        /// <summary>
        /// Test the property 'TimeCreated'
        /// </summary>
        [Test]
        public void TimeCreatedTest()
        {
            // TODO unit test for the property 'TimeCreated'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Sender'
        /// </summary>
        [Test]
        public void SenderTest()
        {
            // TODO unit test for the property 'Sender'
        }
        /// <summary>
        /// Test the property 'Recipient'
        /// </summary>
        [Test]
        public void RecipientTest()
        {
            // TODO unit test for the property 'Recipient'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'SenderCommodityStacks'
        /// </summary>
        [Test]
        public void SenderCommodityStacksTest()
        {
            // TODO unit test for the property 'SenderCommodityStacks'
        }
        /// <summary>
        /// Test the property 'SenderUniqueItems'
        /// </summary>
        [Test]
        public void SenderUniqueItemsTest()
        {
            // TODO unit test for the property 'SenderUniqueItems'
        }
        /// <summary>
        /// Test the property 'RecipientCommodityStacks'
        /// </summary>
        [Test]
        public void RecipientCommodityStacksTest()
        {
            // TODO unit test for the property 'RecipientCommodityStacks'
        }
        /// <summary>
        /// Test the property 'RecipientUniqueItems'
        /// </summary>
        [Test]
        public void RecipientUniqueItemsTest()
        {
            // TODO unit test for the property 'RecipientUniqueItems'
        }

    }

}
