/*
 * EconomyKit API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EconomyKit.UnityClient.Api;
using EconomyKit.UnityClient.Model;
using EconomyKit.UnityClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EconomyKit.UnityClient.Test
{
    /// <summary>
    ///  Class for testing UniqueItemCreateBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UniqueItemCreateBodyTests
    {
        // TODO uncomment below to declare an instance variable for UniqueItemCreateBody
        //private UniqueItemCreateBody instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UniqueItemCreateBody
            //instance = new UniqueItemCreateBody();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UniqueItemCreateBody
        /// </summary>
        [Test]
        public void UniqueItemCreateBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" UniqueItemCreateBody
            //Assert.IsInstanceOf(typeof(UniqueItemCreateBody), instance);
        }


        /// <summary>
        /// Test the property 'Player'
        /// </summary>
        [Test]
        public void PlayerTest()
        {
            // TODO unit test for the property 'Player'
        }
        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Test]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Test]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

    }

}
