/*
 * EconomyKit API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = EconomyKit.UnityClient.Client.OpenAPIDateConverter;

namespace EconomyKit.UnityClient.Model
{
    /// <summary>
    /// CommodityStackResult
    /// </summary>
    [DataContract]
    public partial class CommodityStackResult :  IEquatable<CommodityStackResult>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CommodityStackResult" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CommodityStackResult() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CommodityStackResult" /> class.
        /// </summary>
        /// <param name="quantity">quantity (required).</param>
        /// <param name="commodity">commodity (required).</param>
        public CommodityStackResult(decimal quantity = default(decimal), CommodityResult commodity = default(CommodityResult))
        {
            // to ensure "quantity" is required (not null)
            if (quantity == null)
            {
                throw new InvalidDataException("quantity is a required property for CommodityStackResult and cannot be null");
            }
            else
            {
                this.Quantity = quantity;
            }

            // to ensure "commodity" is required (not null)
            if (commodity == null)
            {
                throw new InvalidDataException("commodity is a required property for CommodityStackResult and cannot be null");
            }
            else
            {
                this.Commodity = commodity;
            }

        }

        /// <summary>
        /// Gets or Sets Quantity
        /// </summary>
        [DataMember(Name="quantity", EmitDefaultValue=true)]
        public decimal Quantity { get; set; }

        /// <summary>
        /// Gets or Sets Commodity
        /// </summary>
        [DataMember(Name="commodity", EmitDefaultValue=true)]
        public CommodityResult Commodity { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CommodityStackResult {\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("  Commodity: ").Append(Commodity).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CommodityStackResult);
        }

        /// <summary>
        /// Returns true if CommodityStackResult instances are equal
        /// </summary>
        /// <param name="input">Instance of CommodityStackResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CommodityStackResult input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Quantity == input.Quantity ||
                    (this.Quantity != null &&
                    this.Quantity.Equals(input.Quantity))
                ) && 
                (
                    this.Commodity == input.Commodity ||
                    (this.Commodity != null &&
                    this.Commodity.Equals(input.Commodity))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Quantity != null)
                    hashCode = hashCode * 59 + this.Quantity.GetHashCode();
                if (this.Commodity != null)
                    hashCode = hashCode * 59 + this.Commodity.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
