/*
 * EconomyKit API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = EconomyKit.UnityClient.Client.OpenAPIDateConverter;

namespace EconomyKit.UnityClient.Model
{
    /// <summary>
    /// Supported ExternalIdentifier types:  - ST: Steam - EG: Epic Games - GC: iOS Game Center - GS: Google Play Game Services - MC: Minecraft (UUID) - EM: Email - DS: Discord - PH: Phone number - PF: PlayFab - XX: Custom payload
    /// </summary>
    /// <value>Supported ExternalIdentifier types:  - ST: Steam - EG: Epic Games - GC: iOS Game Center - GS: Google Play Game Services - MC: Minecraft (UUID) - EM: Email - DS: Discord - PH: Phone number - PF: PlayFab - XX: Custom payload</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum IdentifierType
    {
        /// <summary>
        /// Enum ST for value: ST
        /// </summary>
        [EnumMember(Value = "ST")]
        ST = 1,

        /// <summary>
        /// Enum EG for value: EG
        /// </summary>
        [EnumMember(Value = "EG")]
        EG = 2,

        /// <summary>
        /// Enum GC for value: GC
        /// </summary>
        [EnumMember(Value = "GC")]
        GC = 3,

        /// <summary>
        /// Enum GS for value: GS
        /// </summary>
        [EnumMember(Value = "GS")]
        GS = 4,

        /// <summary>
        /// Enum MC for value: MC
        /// </summary>
        [EnumMember(Value = "MC")]
        MC = 5,

        /// <summary>
        /// Enum EM for value: EM
        /// </summary>
        [EnumMember(Value = "EM")]
        EM = 6,

        /// <summary>
        /// Enum DS for value: DS
        /// </summary>
        [EnumMember(Value = "DS")]
        DS = 7,

        /// <summary>
        /// Enum PH for value: PH
        /// </summary>
        [EnumMember(Value = "PH")]
        PH = 8,

        /// <summary>
        /// Enum PF for value: PF
        /// </summary>
        [EnumMember(Value = "PF")]
        PF = 9,

        /// <summary>
        /// Enum XX for value: XX
        /// </summary>
        [EnumMember(Value = "XX")]
        XX = 10

    }

}
