/*
 * EconomyKit API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = EconomyKit.UnityClient.Client.OpenAPIDateConverter;

namespace EconomyKit.UnityClient.Model
{
    /// <summary>
    /// UniqueItemCreateBody
    /// </summary>
    [DataContract]
    public partial class UniqueItemCreateBody :  IEquatable<UniqueItemCreateBody>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UniqueItemCreateBody" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UniqueItemCreateBody() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UniqueItemCreateBody" /> class.
        /// </summary>
        /// <param name="player">The player to give the item to: if no player is specified, the unique item will not be owned by anyone..</param>
        /// <param name="displayName">The user-facing display name of the new item. (required).</param>
        /// <param name="metadata">Extra, free-form data attached to the new item..</param>
        public UniqueItemCreateBody(Guid player = default(Guid), string displayName = default(string), Object metadata = default(Object))
        {
            // to ensure "displayName" is required (not null)
            if (displayName == null)
            {
                throw new InvalidDataException("displayName is a required property for UniqueItemCreateBody and cannot be null");
            }
            else
            {
                this.DisplayName = displayName;
            }

            this.Player = player;
            this.Metadata = metadata;
        }

        /// <summary>
        /// The player to give the item to: if no player is specified, the unique item will not be owned by anyone.
        /// </summary>
        /// <value>The player to give the item to: if no player is specified, the unique item will not be owned by anyone.</value>
        [DataMember(Name="player", EmitDefaultValue=false)]
        public Guid Player { get; set; }

        /// <summary>
        /// The user-facing display name of the new item.
        /// </summary>
        /// <value>The user-facing display name of the new item.</value>
        [DataMember(Name="display_name", EmitDefaultValue=true)]
        public string DisplayName { get; set; }

        /// <summary>
        /// Extra, free-form data attached to the new item.
        /// </summary>
        /// <value>Extra, free-form data attached to the new item.</value>
        [DataMember(Name="metadata", EmitDefaultValue=false)]
        public Object Metadata { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UniqueItemCreateBody {\n");
            sb.Append("  Player: ").Append(Player).Append("\n");
            sb.Append("  DisplayName: ").Append(DisplayName).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UniqueItemCreateBody);
        }

        /// <summary>
        /// Returns true if UniqueItemCreateBody instances are equal
        /// </summary>
        /// <param name="input">Instance of UniqueItemCreateBody to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UniqueItemCreateBody input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Player == input.Player ||
                    (this.Player != null &&
                    this.Player.Equals(input.Player))
                ) && 
                (
                    this.DisplayName == input.DisplayName ||
                    (this.DisplayName != null &&
                    this.DisplayName.Equals(input.DisplayName))
                ) && 
                (
                    this.Metadata == input.Metadata ||
                    (this.Metadata != null &&
                    this.Metadata.Equals(input.Metadata))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Player != null)
                    hashCode = hashCode * 59 + this.Player.GetHashCode();
                if (this.DisplayName != null)
                    hashCode = hashCode * 59 + this.DisplayName.GetHashCode();
                if (this.Metadata != null)
                    hashCode = hashCode * 59 + this.Metadata.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // DisplayName (string) maxLength
            if(this.DisplayName != null && this.DisplayName.Length > 256)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for DisplayName, length must be less than 256.", new [] { "DisplayName" });
            }


            yield break;
        }
    }

}
