/*
 * EconomyKit API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using EconomyKit.UnityClient.Client;
using EconomyKit.UnityClient.Api;
using EconomyKit.UnityClient.Model;

namespace EconomyKit.UnityClient.Test
{
    /// <summary>
    ///  Class for testing PlayerIDApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class PlayerIDApiTests
    {
        private PlayerIDApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new PlayerIDApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PlayerIDApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' PlayerIDApi
            //Assert.IsInstanceOf(typeof(PlayerIDApi), instance);
        }

        
        /// <summary>
        /// Test CreatePlayer
        /// </summary>
        [Test]
        public void CreatePlayerTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //FetchPlayerRequest fetchPlayerRequest = null;
            //var response = instance.CreatePlayer(fetchPlayerRequest);
            //Assert.IsInstanceOf(typeof(FetchPlayerResponse), response, "response is FetchPlayerResponse");
        }
        
        /// <summary>
        /// Test FetchPlayer
        /// </summary>
        [Test]
        public void FetchPlayerTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //FetchPlayerRequest fetchPlayerRequest = null;
            //var response = instance.FetchPlayer(fetchPlayerRequest);
            //Assert.IsInstanceOf(typeof(FetchPlayerResponse), response, "response is FetchPlayerResponse");
        }
        
    }

}
